Script started on 2020-06-19 18:36:14-06:00
]0;priyavart.rajain1@csa2:~/Downloadspriyavart.rajain1@csa2:~/Downloads$ exitrm project.script./project Minesweeper 7gcc project.s -o project -g3
]0;priyavart.rajain1@csa2:~/Downloadspriyavart.rajain1@csa2:~/Downloads$ gcc project.s -o project -g3exit[Krm project.script./project Minesweeper 7


Hello Minesweeper, Below is the initial game board: 

6.57  4.52  14.06  -12.44  -12.52  -8.68  14.74  
4.88  -0.28  -6.80  14.84  2.53  12.41  0.98  
-14.95  -0.00  10.26  12.43  10.67  14.63  -14.89  
-2.47  4.05  0.81  12.95  4.20  0.19  4.51  
12.05  8.76  0.66  12.85  0.85  0.25  4.49  
12.62  0.31  0.32  14.09  12.85  0.93  10.17  
12.66  2.78  14.55  12.92  0.38  2.22  0.37  

X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    0.00
Time:	   84.00
Enter your move ( x , y ):	0 0

Uncovered a reward of 6.57 points


+ X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    6.57
Time:	   82.00

Press 1 to quit or any other key to continue:    0


+ X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    6.57
Time:	   82.00
Enter your move ( x , y ):	0 1

Uncovered a reward of 4.52 points


+ + X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    11.09
Time:	   80.00

Press 1 to quit or any other key to continue:    0


+ + X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    11.09
Time:	   80.00
Enter your move ( x , y ):	0 3

You discovered a bad surprise, score will be halved.


+ + X ! X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    5.54
Time:	   78.00

Press 1 to quit or any other key to continue:    0


+ + X ! X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    5.54
Time:	   78.00
Enter your move ( x , y ):	0 2

Uncovered a reward of 14.06 points


+ + + ! X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    19.60
Time:	   77.00

Press 1 to quit or any other key to continue:    0


+ + + ! X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    19.60
Time:	   77.00
Enter your move ( x , y ):	0 4

Oops, You lost -12.52 points


+ + + ! - X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    7.08
Time:	   74.00

Press 1 to quit or any other key to continue:    0


+ + + ! - X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    7.08
Time:	   74.00
Enter your move ( x , y ):	0 5

Oops, You lost -8.68 points


+ + + ! - - X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    -1.60
Time:	   72.00
Score went below 0. Game Over


Thanks for playing Minesweeper, Below is your score and time taken: 

Score:    -1.60
Time taken: 12.00
]0;priyavart.rajain1@csa2:~/Downloadspriyavart.rajain1@csa2:~/Downloads$ ./project Minesweeper 7


Hello Minesweeper, Below is the initial game board: 

-4.50  -2.65  10.08  -12.29  -0.39  12.96  -6.37  
-14.75  6.55  -10.52  -2.18  -8.77  10.84  12.88  
8.49  2.38  8.44  6.59  12.70  8.89  0.91  
12.76  6.22  14.50  12.14  8.89  2.62  8.45  
12.26  12.60  6.73  12.21  4.65  8.16  6.53  
12.14  8.00  0.96  2.81  8.10  10.41  12.38  
6.32  2.05  12.51  12.67  6.43  0.23  4.66  

X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    0.00
Time:	   84.00
Enter your move ( x , y ):	0 0

Oops, You lost -4.50 points


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    -4.50
Time:	   78.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    -4.50
Time:	   78.00
Enter your move ( x , y ):	4 0

Uncovered a reward of 12.26 points


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
+ X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    7.76
Time:	   76.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
+ X X X X X X 
X X X X X X X 
X X X X X X X 

Score:    7.76
Time:	   76.00
Enter your move ( x , y ):	4 1

Uncovered a reward of 12.60 points


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
+ + X X X X X 
X X X X X X X 
X X X X X X X 

Score:    20.36
Time:	   75.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
+ + X X X X X 
X X X X X X X 
X X X X X X X 

Score:    20.36
Time:	   75.00
Enter your move ( x , y ):	4 2

Uncovered a reward of 6.73 points


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    27.09
Time:	   73.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X X X X X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    27.09
Time:	   73.00
Enter your move ( x , y ):	3 3

You discovered a nice surprise, score will be doubled.


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X $ X X X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    54.18
Time:	   71.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X $ X X X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    54.18
Time:	   71.00
Enter your move ( x , y ):	0 3 3
 
Cell already discovered, make another choice


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X $ X X X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    54.18
Time:	   66.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X $ X X X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    54.18
Time:	   66.00
Enter your move ( x , y ):	3 5

You discovered a nice surprise, score will be doubled.


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    108.36
Time:	   64.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
X X X X X X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    108.36
Time:	   64.00
Enter your move ( x , y ):	2 0

Uncovered a reward of 8.49 points


- X X X X X X 
X X X X X X X 
+ X X X X X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    116.85
Time:	   62.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
+ X X X X X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    116.85
Time:	   62.00
Enter your move ( x , y ):	2 4

Uncovered a reward of 12.70 points


- X X X X X X 
X X X X X X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    129.55
Time:	   60.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
X X X X X X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    129.55
Time:	   60.00
Enter your move ( x , y ):	1 0

You discovered a time pack. 10 seconds will be added to the timer


- X X X X X X 
@ X X X X X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    129.55
Time:	   69.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
@ X X X X X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    129.55
Time:	   69.00
Enter your move ( x , y ):	1 4

Oops, You lost -8.77 points


- X X X X X X 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    120.78
Time:	   63.00

Press 1 to quit or any other key to continue:    0


- X X X X X X 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    120.78
Time:	   63.00
Enter your move ( x , y ):	0 5

Uncovered a reward of 12.96 points


- X X X X + X 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    133.74
Time:	   61.00

Press 1 to quit or any other key to continue:    0


- X X X X + X 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    133.74
Time:	   61.00
Enter your move ( x , y ):	0 6

Oops, You lost -6.37 points


- X X X X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    127.37
Time:	   59.00

Press 1 to quit or any other key to continue:    0


- X X X X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    127.37
Time:	   59.00
Enter your move ( x , y ):	0 1

You discovered a bad surprise, score will be halved.


- ! X X X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    63.68
Time:	   56.00

Press 1 to quit or any other key to continue:    0


- ! X X X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    63.68
Time:	   56.00
Enter your move ( x , y ):	0 2

Uncovered a reward of 10.08 points


- ! + X X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    73.76
Time:	   53.00

Press 1 to quit or any other key to continue:    0


- ! + X X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    73.76
Time:	   53.00
Enter your move ( x , y ):	0 3

Oops, You lost -12.29 points


- ! + - X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    61.47
Time:	   50.00

Press 1 to quit or any other key to continue:    0


- ! + - X + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    61.47
Time:	   50.00
Enter your move ( x , y ):	0 4

Oops, You lost -0.39 points


- ! + - - + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    61.08
Time:	   49.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ X X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    61.08
Time:	   49.00
Enter your move ( x , y ):	1 1

Uncovered a reward of 6.55 points


- ! + - - + - 
@ + X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    67.63
Time:	   48.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + X X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    67.63
Time:	   48.00
Enter your move ( x , y ):	1 2

You discovered a bad surprise, score will be halved.


- ! + - - + - 
@ + ! X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    33.81
Time:	   47.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! X - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    33.81
Time:	   47.00
Enter your move ( x , y ):	1 3

Oops, You lost -2.18 points


- ! + - - + - 
@ + ! - - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    31.63
Time:	   42.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - X X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    31.63
Time:	   42.00
Enter your move ( x , y ):	1 5

You discovered a time pack. 10 seconds will be added to the timer


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    31.63
Time:	   50.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X X X 
X X X X X X X 

Score:    31.63
Time:	   50.00
Enter your move ( x , y ):	5 5

Uncovered a reward of 10.41 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X + X 
X X X X X X X 

Score:    42.04
Time:	   47.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X + X 
X X X X X X X 

Score:    42.04
Time:	   47.00
Enter your move ( x , y ):	6 6

Uncovered a reward of 4.66 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X + X 
X X X X X X + 

Score:    46.70
Time:	   45.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X X + X 
X X X X X X + 

Score:    46.70
Time:	   45.00
Enter your move ( x , y ):	5 4

Uncovered a reward of 8.10 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X + + X 
X X X X X X + 

Score:    54.80
Time:	   36.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X X + + X 
X X X X X X + 

Score:    54.80
Time:	   36.00
Enter your move ( x , y ):	5 3

Uncovered a reward of 2.81 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
X X X X X X + 

Score:    57.61
Time:	   34.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
X X X X X X + 

Score:    57.61
Time:	   34.00
Enter your move ( x , y ):	6 0

Uncovered a reward of 6.32 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ X X X X X + 

Score:    63.93
Time:	   32.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ X X X X X + 

Score:    63.93
Time:	   32.00
Enter your move ( x , y ):	6 1

Uncovered a reward of 2.05 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + X X X X + 

Score:    65.98
Time:	   30.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + X X X X + 

Score:    65.98
Time:	   30.00
Enter your move ( x , y ):	6 2

Uncovered a reward of 12.51 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + X X X + 

Score:    78.49
Time:	   28.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + X X X + 

Score:    78.49
Time:	   28.00
Enter your move ( x , y ):	6 3

Uncovered a reward of 12.67 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + X X + 

Score:    91.16
Time:	   26.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + X X + 

Score:    91.16
Time:	   26.00
Enter your move ( x , y ):	6 4

Uncovered a reward of 6.43 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + + X + 

Score:    97.59
Time:	   24.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + + X + 

Score:    97.59
Time:	   24.00
Enter your move ( x , y ):	6 4
 
Cell already discovered, make another choice


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + + X + 

Score:    97.59
Time:	   23.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + + X + 

Score:    97.59
Time:	   23.00
Enter your move ( x , y ):	6
5

Uncovered a reward of 0.23 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + + + + 

Score:    97.82
Time:	   20.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
X X X + + + X 
+ + + + + + + 

Score:    97.82
Time:	   20.00
Enter your move ( x , y ):	5 0

Uncovered a reward of 12.14 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ X X + + + X 
+ + + + + + + 

Score:    109.96
Time:	   18.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ X X + + + X 
+ + + + + + + 

Score:    109.96
Time:	   18.00
Enter your move ( x , y ):	5 1

Uncovered a reward of 8.00 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ + X + + + X 
+ + + + + + + 

Score:    117.96
Time:	   17.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ + X + + + X 
+ + + + + + + 

Score:    117.96
Time:	   17.00
Enter your move ( x , y ):	5 2

Uncovered a reward of 0.96 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ + + + + + X 
+ + + + + + + 

Score:    118.92
Time:	   14.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ + + + + + X 
+ + + + + + + 

Score:    118.92
Time:	   14.00
Enter your move ( x , y ):	5 6

Uncovered a reward of 12.38 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ + + + + + + 
+ + + + + + + 

Score:    131.30
Time:	   12.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X X 
+ + + + + + + 
+ + + + + + + 

Score:    131.30
Time:	   12.00
Enter your move ( x , y ):	4 6

Uncovered a reward of 6.53 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X + 
+ + + + + + + 
+ + + + + + + 

Score:    137.83
Time:	   10.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X X + 
+ + + + + + + 
+ + + + + + + 

Score:    137.83
Time:	   10.00
Enter your move ( x , y ):	5 5   4 5

Uncovered a reward of 8.16 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X + + 
+ + + + + + + 
+ + + + + + + 

Score:    145.99
Time:	   6.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + X X + + 
+ + + + + + + 
+ + + + + + + 

Score:    145.99
Time:	   6.00
Enter your move ( x , y ):	4 3

Uncovered a reward of 12.21 points


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + + X + + 
+ + + + + + + 
+ + + + + + + 

Score:    158.20
Time:	   3.00

Press 1 to quit or any other key to continue:    0


- ! + - - + - 
@ + ! - - @ X 
+ X X X + X X 
X X X $ X $ X 
+ + + + X + + 
+ + + + + + + 
+ + + + + + + 

Score:    158.20
Time:	   3.00
Enter your move ( x , y ):	3 3 0

Time Up. Game Over


Thanks for playing Minesweeper, Below is your score and time taken: 

Score:    158.20
Time taken: 84.00
]0;priyavart.rajain1@csa2:~/Downloadspriyavart.rajain1@csa2:~/Downloads$ ./project Minesweeper 7[K5


Hello Minesweeper, Below is the initial game board: 

-2.40  -8.71  4.66  -8.34  -12.68  
8.19  14.43  14.52  0.31  12.46  
4.93  14.49  2.65  12.58  14.07  
4.99  10.42  0.81  8.74  6.47  
10.65  8.52  6.15  12.20  2.91  

X X X X X 
X X X X X 
X X X X X 
X X X X X 
X X X X X 

Score:    0.00
Time:	   60.00
Enter your move ( x , y ):	4 4

Uncovered a reward of 2.91 points


X X X X X 
X X X X X 
X X X X X 
X X X X X 
X X X X + 

Score:    2.91
Time:	   57.00

Press 1 to quit or any other key to continue:    0


X X X X X 
X X X X X 
X X X X X 
X X X X X 
X X X X + 

Score:    2.91
Time:	   57.00
Enter your move ( x , y ):	3 3

Uncovered a reward of 8.74 points


X X X X X 
X X X X X 
X X X X X 
X X X + X 
X X X X + 

Score:    11.65
Time:	   56.00

Press 1 to quit or any other key to continue:    0


X X X X X 
X X X X X 
X X X X X 
X X X + X 
X X X X + 

Score:    11.65
Time:	   56.00
Enter your move ( x , y ):	0 0

Oops, You lost -2.40 points


- X X X X 
X X X X X 
X X X X X 
X X X + X 
X X X X + 

Score:    9.25
Time:	   55.00

Press 1 to quit or any other key to continue:    0


- X X X X 
X X X X X 
X X X X X 
X X X + X 
X X X X + 

Score:    9.25
Time:	   55.00
Enter your move ( x , y ):	0 4

Oops, You lost -12.68 points


- X X X - 
X X X X X 
X X X X X 
X X X + X 
X X X X + 

Score:    -3.43
Time:	   53.00
Score went below 0. Game Over


Thanks for playing Minesweeper, Below is your score and time taken: 

Score:    -3.43
Time taken: 7.00
]0;priyavart.rajain1@csa2:~/Downloadspriyavart.rajain1@csa2:~/Downloads$ ./project Minesweeper 5


Hello Minesweeper, Below is the initial game board: 

-12.76  -10.31  -2.87  0.22  -12.51  
8.94  14.08  12.95  0.49  14.63  
8.79  10.17  10.25  12.06  14.34  
6.10  4.05  0.25  8.70  0.58  
10.18  2.88  14.51  6.71  8.93  

X X X X X 
X X X X X 
X X X X X 
X X X X X 
X X X X X 

Score:    0.00
Time:	   60.00
Enter your move ( x , y ):	1 2

Uncovered a reward of 12.95 points


X X X X X 
X X + X X 
X X X X X 
X X X X X 
X X X X X 

Score:    12.95
Time:	   57.00

Press 1 to quit or any other key to continue:    0


X X X X X 
X X + X X 
X X X X X 
X X X X X 
X X X X X 

Score:    12.95
Time:	   57.00
Enter your move ( x , y ):	1 3

Uncovered a reward of 0.49 points


X X X X X 
X X + + X 
X X X X X 
X X X X X 
X X X X X 

Score:    13.44
Time:	   56.00

Press 1 to quit or any other key to continue:    0


X X X X X 
X X + + X 
X X X X X 
X X X X X 
X X X X X 

Score:    13.44
Time:	   56.00
Enter your move ( x , y ):	1 4

You discovered a time pack. 10 seconds will be added to the timer


X X X X X 
X X + + @ 
X X X X X 
X X X X X 
X X X X X 

Score:    13.44
Time:	   65.00

Press 1 to quit or any other key to continue:    0


X X X X X 
X X + + @ 
X X X X X 
X X X X X 
X X X X X 

Score:    13.44
Time:	   65.00
Enter your move ( x , y ):	3 0

You discovered a time pack. 10 seconds will be added to the timer


X X X X X 
X X + + @ 
X X X X X 
@ X X X X 
X X X X X 

Score:    13.44
Time:	   72.00

Press 1 to quit or any other key to continue:    0


X X X X X 
X X + + @ 
X X X X X 
@ X X X X 
X X X X X 

Score:    13.44
Time:	   72.00
Enter your move ( x , y ):	3 4

Uncovered a reward of 0.58 points


X X X X X 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    14.02
Time:	   71.00

Press 1 to quit or any other key to continue:    0


X X X X X 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    14.02
Time:	   71.00
Enter your move ( x , y ):	0 0

You discovered a time pack. 10 seconds will be added to the timer


@ X X X X 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    14.02
Time:	   80.00

Press 1 to quit or any other key to continue:    0


@ X X X X 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    14.02
Time:	   80.00
Enter your move ( x , y ):	3 4
 
Cell already discovered, make another choice


@ X X X X 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    14.02
Time:	   78.00

Press 1 to quit or any other key to continue:    0


@ X X X X 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    14.02
Time:	   78.00
Enter your move ( x , y ):	1   0 4

Oops, You lost -12.51 points


@ X X X - 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    1.51
Time:	   74.00

Press 1 to quit or any other key to continue:    0


@ X X X - 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    1.51
Time:	   74.00
Enter your move ( x , y ):	0 3

Uncovered a reward of 0.22 points


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    1.73
Time:	   72.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
X X X X X 

Score:    1.73
Time:	   72.00
Enter your move ( x , y ):	4 3

Uncovered a reward of 6.71 points


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
X X X + X 

Score:    8.44
Time:	   69.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
X X X + X 

Score:    8.44
Time:	   69.00
Enter your move ( x , y ):	3 4 4

Uncovered a reward of 8.93 points


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
X X X + + 

Score:    17.37
Time:	   68.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
X X X + + 

Score:    17.37
Time:	   68.00
Enter your move ( x , y ):	4 0

Uncovered a reward of 10.18 points


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
+ X X + + 

Score:    27.55
Time:	   67.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
+ X X + + 

Score:    27.55
Time:	   67.00
Enter your move ( x , y ):	4 1

Uncovered a reward of 2.88 points


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
+ + X + + 

Score:    30.43
Time:	   65.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
+ + X + + 

Score:    30.43
Time:	   65.00
Enter your move ( x , y ):	4 2

Uncovered a reward of 14.51 points


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
+ + + + + 

Score:    44.94
Time:	   64.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ X X X + 
+ + + + + 

Score:    44.94
Time:	   64.00
Enter your move ( x , y ):	3 2

Uncovered a reward of 0.25 points


@ X X + - 
X X + + @ 
X X X X X 
@ X + X + 
+ + + + + 

Score:    45.19
Time:	   62.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ X + X + 
+ + + + + 

Score:    45.19
Time:	   62.00
Enter your move ( x , y ):	3 1

Uncovered a reward of 4.05 points


@ X X + - 
X X + + @ 
X X X X X 
@ + + X + 
+ + + + + 

Score:    49.24
Time:	   61.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ + + X + 
+ + + + + 

Score:    49.24
Time:	   61.00
Enter your move ( x , y ):	4 3 2
 
Cell already discovered, make another choice


@ X X + - 
X X + + @ 
X X X X X 
@ + + X + 
+ + + + + 

Score:    49.24
Time:	   57.00

Press 1 to quit or any other key to continue:    - 0


@ X X + - 
X X + + @ 
X X X X X 
@ + + X + 
+ + + + + 

Score:    49.24
Time:	   57.00
Enter your move ( x , y ):	3 3

Uncovered a reward of 8.70 points


@ X X + - 
X X + + @ 
X X X X X 
@ + + + + 
+ + + + + 

Score:    57.94
Time:	   56.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
X X X X X 
@ + + + + 
+ + + + + 

Score:    57.94
Time:	   56.00
Enter your move ( x , y ):	2 0

Uncovered a reward of 8.79 points


@ X X + - 
X X + + @ 
+ X X X X 
@ + + + + 
+ + + + + 

Score:    66.73
Time:	   54.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
+ X X X X 
@ + + + + 
+ + + + + 

Score:    66.73
Time:	   54.00
Enter your move ( x , y ):	2 1

Uncovered a reward of 10.17 points


@ X X + - 
X X + + @ 
+ + X X X 
@ + + + + 
+ + + + + 

Score:    76.90
Time:	   53.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
+ + X X X 
@ + + + + 
+ + + + + 

Score:    76.90
Time:	   53.00
Enter your move ( x , y ):	2 3 2

Uncovered a reward of 10.25 points


@ X X + - 
X X + + @ 
+ + + X X 
@ + + + + 
+ + + + + 

Score:    87.15
Time:	   52.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
+ + + X X 
@ + + + + 
+ + + + + 

Score:    87.15
Time:	   52.00
Enter your move ( x , y ):	2 3

Uncovered a reward of 12.06 points


@ X X + - 
X X + + @ 
+ + + + X 
@ + + + + 
+ + + + + 

Score:    99.21
Time:	   51.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
+ + + + X 
@ + + + + 
+ + + + + 

Score:    99.21
Time:	   51.00
Enter your move ( x , y ):	2 4

Uncovered a reward of 14.34 points


@ X X + - 
X X + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    113.55
Time:	   49.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
X X + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    113.55
Time:	   49.00
Enter your move ( x , y ):	1 0

Uncovered a reward of 8.94 points


@ X X + - 
+ X + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    122.49
Time:	   46.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
+ X + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    122.49
Time:	   46.00
Enter your move ( x , y ):	1 1

Uncovered a reward of 14.08 points


@ X X + - 
+ + + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    136.57
Time:	   44.00

Press 1 to quit or any other key to continue:    0


@ X X + - 
+ + + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    136.57
Time:	   44.00
Enter your move ( x , y ):	0 1

Oops, You lost -10.31 points


@ - X + - 
+ + + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    126.26
Time:	   43.00

Press 1 to quit or any other key to continue:    0


@ - X + - 
+ + + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    126.26
Time:	   43.00
Enter your move ( x , y ):	0 2

Oops, You lost -2.87 points


@ - - + - 
+ + + + @ 
+ + + + + 
@ + + + + 
+ + + + + 

Score:    123.39
Time:	   41.00

All cells have been discovered. Game Over


Thanks for playing Minesweeper, Below is your score and time taken: 

Score:    123.39
Time taken: 19.00
]0;priyavart.rajain1@csa2:~/Downloadspriyavart.rajain1@csa2:~/Downloads$ quit
bash: quit: command not found
]0;priyavart.rajain1@csa2:~/Downloadspriyavart.rajain1@csa2:~/Downloads$ exit
exit

Script done on 2020-06-19 18:42:15-06:00
